version: "3"

services:

  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.3.3
    expose: 
      - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
    volumes:
      - "nbxplorer_datadir:/datadir"

volumes:
    nbxplorer_datadir: